import type { Metadata } from "next";
import { Gelasio, Karla } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Header from "@/components/Header";

const gelasio = Gelasio({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-gelasio",
});
const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${gelasio.variable} ${karla.variable} antialiased dark`}
      >
        {/* Header și Navbar fixate deasupra conținutului */}
        <div className="fixed top-0 left-0 w-full z-50 bg-transparent">
          <Header />
          <Navbar />
        </div>

        {/* Conținut principal cu padding pentru header */}
        <main className="pt-[140px] min-h-screen relative z-0">{children}</main>
      </body>
    </html>
  );
}
