import type { Metadata } from "next";
import { Gelasio, Karla } from "next/font/google";
import "./globals.css";

const gelasio = Gelasio({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-gelasio",
});
const karla = Karla({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-karla",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body
        className={`${gelasio.variable} ${karla.variable} antialiased dark`}
      >
        {/* Conținut principal */}
        <main className="">{children}</main>
      </body>
    </html>
  );
}
